version: '3'

services:
  backend:
    build: ./backend
    container_name: melwood_backend
    ports:
      - 4000:4000
    tty: true
    volumes:
      - ./backend:/app
    working_dir: /app
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: melwood_frontend
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./frontend:/app
    working_dir: /app
    networks:
      - app-network

networks:
  app-network:
    external: true
