version: '3'

services:
  nextjs:
    build: .
    container_name: melwood
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    env_file:
      - .env
    working_dir: /app
    command: npm run dev
