version: '3'

services:
  backend:
    build: ./backend
    container_name: melwood_backend
    ports:
      - 4000:4000
    tty: true
    volumes:
      - ./backend/src:/app/src
      - ./backend/public:/app/public
    working_dir: /app
    command: node src/server.js
