version: '3'

services:
  app:
    build: ./src
    container_name: melwood_app
    ports:
      - 8088:8080
    working_dir: /app
    tty: true
    depends_on:
      - db
    volumes:
      - ./src:/app
    networks:
      - app-network

  db:
    image: mongo:latest
    container_name: melwood_db
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./data/db:/data/db
    command:
      - mongod
    networks:
      - app-network

networks:
  app-network:
    external: true
