version: '3'

services:
  db:
    image: mongo:latest
    container_name: melwood_db
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build: ./
    container_name: melwood_app
    ports:
      - "8081:8080"
    restart: always
    working_dir: /usr/src/app
    depends_on:
      - db
