version: '3'

services:
  app:
    build: ./docker/
    container_name: melwood_app
    volumes:
      - ./frontend:/app
    ports:
      - 4000:3000
    tty: true
    command: "yarn dev"

networks:
  app-network:
    external: true
