version: '3'

services:
  app:
    build: .
    container_name: melwood_app
    volumes:
      - ./app:/app
    ports:
      - 4000:3000
    tty: true
    # command: "yarn dev"
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: melwood_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: melwood_db
      MYSQL_USER: mel
      MYSQL_PASSWORD: wood
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 4306:3306
    networks:
      - app-network

networks:
  app-network:
    external: true
