version: '3'

services:
  backend:
    build: ./backend
    container_name: melwood_backend
    ports:
      - 4000:4000
    volumes:
      - ./backend/src:/app/src
      - ./backend/public:/app/public
    working_dir: /app
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: melwood_frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    working_dir: /app
    command: npm run dev
